networks:
  ros:
    driver: bridge

services:

  slam:
    image: curly/torch_slam:latest
    container_name: slam
    network_mode: host
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
    working_dir: "/workspace"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/${USER}/.Xauthority:rw
      - .zshrc:/root/.zshrc:rw
      - .zsh_history:/root/.zsh_history:rw
      - $HOME/Projects/:/workspace/Projects/
      - $HOME/data:/data/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: /bin/zsh
